language: python

notifications:
  email: false

python:
  - '3.6'
  - '3.7'

dist: xenial

before_script:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt

script:
  # Install and build package
  - pip install -e .
  # Run tests
  - pytest --cov=pysofa2
  # - pytest --cov=pysofa2 --cov-report html:coverage_report --cov-report term tests
  # - travis-sphinx --outdir docs/build build --source docs/source

after_success:
  - coveralls
  # - travis-sphinx --outdir docs/build deploy

deploy:
  provider: pypi
  user: $TWINE_USERNAME
  password: $TWINE_PASSWORD
  on:
    tags: true
  skip_existing: true