language: python
notifications:
  email: false
python:
- '3.6'
- '3.7'
- '3.8'
dist: xenial
before_script:
- pip install -U -r requirements.txt
- pip install -U -r requirements-dev.txt
script:
- pip install -e .
- pytest --cov=pysofa2
after_success:
- coveralls
deploy:
  provider: pypi
  user:
    secure: B5ne6uONJRoXu5HusDIB8M4Jhw56JO6H4u5QVmi7Qi1Yd9rC0CMQcB1XqyTlp8G7TMsjzhZI1NG8lJEH5An4K/q89wEeQxBHdvhV87LYHq3LSd68thI1tNNfg4Ab3KKKJxIXjAyRn9ydEmxD1J5XtYo/xTpS9wkWTJUXvSaXzL/wxpJKHS93otqQoMqeBnlXZQLhnHC9RIk0i5v4I8OTQ/82iFvRdmd/qDbCgeEs9lhOkeE6UgQQbR1sxiZQU00lmuPjQpwhl3zeLW2IxChyyb69ZfG8hOHB3s/n4TCIEifVarxnBuj6cr1xkvi8Zfh91AaP1wOb5hxBHkyTFcuVUJ58LXZZ/cJBOwrbff0DeB3hAhKX9i6IgwRBJRXUh05aycxkGiRxo0YrRq0h5pjnwf7G6ljHQNiXkd1JTysUroBnLQifYmK7HI5cqK922cm0n4H9uwRxiHdchERVKG2ZrHL7pZCL+NnztIzG80QKyyzQbLbaPwBQ+py8O4eiW0zRdSbWdTgGXBCf706U72n2UpBx70Bfr+dsmwVMYlt9/YSzpUrvqSLSdsRtElcmzxBVe7LwoW8h7iZI9gdejVW28zaGM5PQrmpi3Lc8XbN8D/1QSyqRD3lbrpeBIjWrbyKzXA2U3USU4CbGJ4hDvYiopM2Qn8mALJU/fmFF/mo/uAQ=
  password:
    secure: hBkmu5QKLlq8qhg92SoHFdXv2hw9eVzNWsS7bGaf8ueW9n2xhrFUYEmmGQH9Jmap4gHgvz1BkdgDJLM/vLcmY776QvL1vVhMFSHRUG0uZG2gtf0MiCN9+hIzyBRqdSgcq7PST6qMfwsnWEFqLFBiWKVPWtV65TjaWCBFMMlKXBcrGWvBfzK+in+Cnmo9cVx78QMpekEt+ntbG8JoprwRycN2n0h56LZ+LbHWnglnvdCCij0RWsdvAgDml0q3P99fSaRdg4AIqZtnncdqdA81HQ7hyJfogML/CfIla9Uc1oKi+ycLDnh4hWoVJEqa9uTXO68DXmzZH+DHlntZvyvXyC6y3uPVxO3C8iMxepiTl+2Av1D+1pkeooQfK5dQk8s7D2KNY/OGGDbIdZyWF9nDMrD/yp6J5AK3V1DwO2O+TBKGaOS4JV/rCIa7lPZGw8L8mz1lXlAPtwQSdWyw6965t4Y2LODNgOZhgMM03FQznbevsR8tiedDAOW/cWmPbv8YPFIjoHe4yydXSN3uzB+UED2AjjZx3bKpbiGOqPamMtzqx83j4WlXyGMx8Rtb4a5gNAXYzLJM9Ipc3/gHxmi3FsdInze3/NGgHA3jFxXkpAi8czGXNUdYC6jRTHiU+dPrCgpNMySY4YCPT9/SRvxbh8JOuuEcUNhFdWSFLrugBJM=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true